#!/usr/bin/env ruby

require 'irb'
require 'irb/completion'

$:.unshift "#{File.dirname(__FILE__)}/../config"

def reload!
  eval(File.read("#{File.dirname(__FILE__)}/../config/application.rb").gsub('require_relative', 'load'))
end

reload!

require 'byebug'

IRB.start